USE qlbh_onl
GO

CREATE ROLE manager
GRANT CONTROL ON DATABASE::qlbh_onl TO manager;
DROP ROLE manager

CREATE LOGIN ptthua WITH PASSWORD='123456'
CREATE USER ptthua FOR LOGIN ptthua
ALTER ROLE [db_owner] ADD MEMBER ptthua
DROP LOGIN ptthua

DROP ROLE ROLE_PARTNER
CREATE ROLE ROLE_PARTNER
GRANT UPDATE,SELECT ON OBJECT::DBO.PARTNERS TO ROLE_PARTNER
GRANT SELECT ON OBJECT::DBO.CONTRACTS TO ROLE_PARTNER
GRANT SELECT ON OBJECT::DBO.RENEWAL_REC TO ROLE_PARTNER
GRANT UPDATE ON OBJECT::DBO.CONTRACTS(ContractID, PartnerID, Sales, Duration, CommissionP) TO ROLE_PARTNER
GRANT SELECT, INSERT, UPDATE, DELETE ON OBJECT::DBO.PRODUCT TO ROLE_PARTNER
GRANT SELECT ON OBJECT::DBO.RECEIPT TO ROLE_PARTNER
GRANT UPDATE ON OBJECT::DBO.RECEIPT(ReceiptStatus) TO ROLE_PARTNER

CREATE ROLE ROLE_CUSTOMER
GRANT UPDATE,SELECT ON OBJECT::DBO.CUSTOMER TO ROLE_CUSTOMER
GRANT SELECT ON OBJECT::DBO.PARTNERS TO ROLE_CUSTOMER
GRANT SELECT ON OBJECT::DBO.PRODUCT TO ROLE_CUSTOMER
GRANT SELECT ON OBJECT::DBO.RECEIPT TO ROLE_CUSTOMER

CREATE ROLE ROLE_SHIPPER
GRANT UPDATE,SELECT ON OBJECT::DBO.SHIPPER TO ROLE_SHIPPER
GRANT SELECT ON OBJECT::DBO.RECEIPT TO ROLE_SHIPPER
GRANT UPDATE ON OBJECT::DBO.RECEIPT(ReceiptStatus) TO ROLE_SHIPPER
GRANT SELECT ON OBJECT::DBO.DELIVERY_NOTE TO ROLE_SHIPPER
GRANT SELECT ON OBJECT::DBO.DELIVERY_DETAIL TO ROLE_SHIPPER

CREATE ROLE ROLE_STAFF
GRANT SELECT ON OBJECT::DBO.RENEWAL_REC TO ROLE_PARTNER
GRANT SELECT, UPDATE ON OBJECT::DBO.CONTRACTS TO ROLE_PARTNER