USE qlbh_onl
GO
/*DROP USER userDT
DROP ROLE ROLE_PARTNER
DROP LOGIN DT
DROP USER userAD
DROP LOGIN AD
DROP USER userNV
DROP ROLE ROLE_STAFF
DROP LOGIN NV
DROP USER userKH
DROP ROLE ROLE_CUSTOMER
DROP LOGIN KH
DROP USER userTX
DROP ROLE ROLE_SHIPPER
DROP LOGIN TX*/
EXEC SP_ADDLOGIN 'AD', 'AD'
GO
CREATE USER userAD FOR LOGIN AD
GO
EXEC Sp_addRoleMember db_owner, userAD
GO
CREATE ROLE ROLE_STAFF
GRANT SELECT ON OBJECT::DBO.RENEWAL_REC TO ROLE_STAFF WITH GRANT OPTION
GRANT SELECT, UPDATE ON OBJECT::DBO.CONTRACTS TO ROLE_STAFF WITH GRANT OPTION
GO
EXEC SP_ADDLOGIN 'NV', 'NV'
GO
CREATE USER userNV FOR LOGIN NV
GO
EXEC SP_ADDROLEMEMBER ROLE_STAFF, userNV
GO
CREATE ROLE ROLE_PARTNER
GRANT UPDATE,SELECT ON OBJECT::DBO.PARTNERS TO ROLE_PARTNER
GRANT SELECT ON OBJECT::DBO.RENEWAL_REC TO ROLE_PARTNER
GRANT SELECT,INSERT ON OBJECT::DBO.CONTRACTS TO ROLE_PARTNER
GRANT UPDATE(Sales, Duration, CommissionP) ON OBJECT::DBO.CONTRACTS TO ROLE_PARTNER
GRANT SELECT, INSERT, UPDATE, DELETE ON OBJECT::DBO.PRODUCT TO ROLE_PARTNER WITH GRANT OPTION
GRANT SELECT ON OBJECT::DBO.RECEIPT TO ROLE_PARTNER
GRANT UPDATE ON OBJECT::DBO.RECEIPT(ReceiptStatus) TO ROLE_PARTNER
GRANT SELECT, INSERT, UPDATE, DELETE ON OBJECT::DBO.BRANCH TO ROLE_PARTNER WITH GRANT OPTION
GRANT SELECT, INSERT, UPDATE, DELETE ON OBJECT::DBO.STORAGE TO ROLE_PARTNER WITH GRANT OPTION
GRANT EXECUTE ON pr_getProductByPartner TO ROLE_PARTNER
GRANT EXECUTE ON pr_ProductUpd TO ROLE_PARTNER
GRANT EXECUTE ON pr_InsProd TO ROLE_PARTNER
GO
EXEC SP_ADDLOGIN 'DT', 'DT'
GO
CREATE USER userDT FOR LOGIN DT
GO
EXEC Sp_addRoleMember ROLE_PARTNER, userDT
GO
CREATE ROLE ROLE_CUSTOMER
GRANT UPDATE,SELECT ON OBJECT::DBO.CUSTOMER TO ROLE_CUSTOMER
GRANT SELECT ON OBJECT::DBO.PARTNERS TO ROLE_CUSTOMER
GRANT SELECT ON OBJECT::DBO.PRODUCT TO ROLE_CUSTOMER
GRANT INSERT, SELECT ON OBJECT::DBO.RECEIPT TO ROLE_CUSTOMER
GRANT INSERT, SELECT ON OBJECT::DBO.RECEIPT_DETAIL TO ROLE_CUSTOMER
GRANT EXECUTE ON pr_getProductByType TO ROLE_CUSTOMER
GRANT EXECUTE ON pr_OrderConfirmation TO ROLE_CUSTOMER
GRANT EXECUTE ON pr_addRDetail TO ROLE_CUSTOMER
GRANT EXECUTE ON AUTO_ReceiptID TO ROLE_CUSTOMER
GO
EXEC SP_ADDLOGIN 'KH', 'KH'
GO
CREATE USER userKH FOR LOGIN KH
GO
EXEC Sp_addRoleMember ROLE_CUSTOMER, userKH
GO   
CREATE ROLE ROLE_SHIPPER
GRANT UPDATE,SELECT ON OBJECT::DBO.SHIPPER TO ROLE_SHIPPER
GRANT SELECT ON OBJECT::DBO.RECEIPT TO ROLE_SHIPPER
GRANT SELECT ON OBJECT::DBO.CUSTOMER TO ROLE_SHIPPER
GRANT UPDATE ON OBJECT::DBO.RECEIPT(ReceiptStatus) TO ROLE_SHIPPER
GRANT SELECT,INSERT,DELETE ON OBJECT::DBO.DELIVERY_NOTE TO ROLE_SHIPPER
GRANT EXECUTE ON pr_getReceipt TO ROLE_SHIPPER
GRANT EXECUTE ON pr_getReceiptByDistrict TO ROLE_SHIPPER
GRANT EXECUTE ON pr_getDeliveryNote TO ROLE_SHIPPER
GO
EXEC SP_ADDLOGIN 'TX', 'TX'
GO
CREATE USER userTX FOR LOGIN TX
GO
EXEC Sp_addRoleMember ROLE_SHIPPER, userTX
GO  