/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package supermarket;

import java.awt.Image;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.ArrayList;
import java.sql.Statement;
import java.sql.ResultSet;
//import java.sql.Driver;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableModel;

/**
 *
 * @author ranco
 */
public class ShowProduct extends javax.swing.JFrame {

    /**
     * Creates new form ShowProduct
     */
    public ShowProduct() throws IOException {
        initComponents();
        populateJTable();
//        SelectProduct();
    }
    
//    ArrayList <ListOfProducts> classList = new ArrayList <ListOfProducts>();
    Connection Con = null;
    Statement St = null;
    ResultSet Rs = null;
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ProductTable = new javax.swing.JTable();
        nameVar = new javax.swing.JTextField();
        fillterBox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        priceVar = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        AddBtn = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        ProductTable2 = new javax.swing.JTable();
        RefreshBtn = new javax.swing.JButton();
        billVar = new javax.swing.JLabel();
        paymentVar = new javax.swing.JLabel();
        allPaymentVar = new javax.swing.JLabel();
        clearBillBtn = new javax.swing.JButton();
        confirmBtn = new javax.swing.JButton();
        quanVar2 = new javax.swing.JSpinner();
        cardVar = new javax.swing.JRadioButton();
        cashVar = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        ProductTable.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ProductTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Unit", "Price", "NoInventory", "Image"
            }
        ));
        ProductTable.setGridColor(new java.awt.Color(153, 153, 255));
        ProductTable.setShowGrid(false);
        ProductTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProductTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ProductTable);

        nameVar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        nameVar.setForeground(new java.awt.Color(153, 153, 255));
        nameVar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameVarActionPerformed(evt);
            }
        });

        fillterBox.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        fillterBox.setForeground(new java.awt.Color(153, 153, 255));
        fillterBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lower 50k", "50k to 500k", "Higher 500k", "Stationery", "Electric Appliances", "Kitchen Utensils & Appliances", "Phone Accessories", "Detergents", "Beauty & Personal Care", "Food", "Beverage", "All" }));
        fillterBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fillterBoxActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 255));
        jLabel6.setText("Fillter by:");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 255));
        jLabel2.setText("Name:");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 255));
        jLabel7.setText("Shopping Cart");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 255));
        jLabel3.setText("Price:");

        priceVar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        priceVar.setForeground(new java.awt.Color(153, 153, 255));
        priceVar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceVarActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 153, 255));
        jLabel8.setText("Quantity:");

        AddBtn.setBackground(new java.awt.Color(0, 255, 51));
        AddBtn.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        AddBtn.setText("Add");
        AddBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddBtnMouseClicked(evt);
            }
        });
        AddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBtnActionPerformed(evt);
            }
        });

        ProductTable2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ProductTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PRODUCT", "PRICE", "QUANTITY", "TOTAL"
            }
        ));
        jScrollPane4.setViewportView(ProductTable2);

        RefreshBtn.setText("Refresh");
        RefreshBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RefreshBtnMouseClicked(evt);
            }
        });
        RefreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshBtnActionPerformed(evt);
            }
        });

        billVar.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        billVar.setForeground(new java.awt.Color(153, 153, 255));
        billVar.setText("Your bill: ");

        paymentVar.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        paymentVar.setForeground(new java.awt.Color(153, 153, 255));
        paymentVar.setText("Your fee: ");

        allPaymentVar.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        allPaymentVar.setForeground(new java.awt.Color(153, 153, 255));
        allPaymentVar.setText("All Payment is:");

        clearBillBtn.setBackground(new java.awt.Color(255, 51, 0));
        clearBillBtn.setText("Clear Cart");
        clearBillBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearBillBtnMouseClicked(evt);
            }
        });
        clearBillBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBillBtnActionPerformed(evt);
            }
        });

        confirmBtn.setBackground(new java.awt.Color(0, 255, 51));
        confirmBtn.setText("Confirm");
        confirmBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                confirmBtnMouseClicked(evt);
            }
        });
        confirmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmBtnActionPerformed(evt);
            }
        });

        quanVar2.setModel(new javax.swing.SpinnerNumberModel());

        buttonGroup1.add(cardVar);
        cardVar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cardVar.setText("By Card");
        cardVar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardVarActionPerformed(evt);
            }
        });

        buttonGroup1.add(cashVar);
        cashVar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cashVar.setSelected(true);
        cashVar.setText("By cash");
        cashVar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashVarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(confirmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(RefreshBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(fillterBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(cashVar)
                                        .addGap(29, 29, 29)
                                        .addComponent(cardVar))
                                    .addComponent(billVar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(paymentVar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(allPaymentVar, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 247, Short.MAX_VALUE))
                            .addComponent(jScrollPane1))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(clearBillBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(210, 210, 210))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameVar, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(priceVar, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(quanVar2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addGap(90, 90, 90))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(197, 197, 197))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(AddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(RefreshBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fillterBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameVar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(priceVar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(quanVar2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(AddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(billVar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(paymentVar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(allPaymentVar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cardVar)
                            .addComponent(cashVar))
                        .addGap(55, 55, 55)
                        .addComponent(confirmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(clearBillBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        jLabel9.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("X");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SHOPPING");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PEELADAZ");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("PEELADAZ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 533, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(323, 323, 323)
                        .addComponent(jLabel9)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(487, 487, 487)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(596, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(280, 280, 280)
                    .addComponent(jLabel4)
                    .addContainerGap(482, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void cashVarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashVarActionPerformed
        // TODO add your handling code here:
        if (cashVar.isSelected() == true){
            cashAndCard = true;
        }
    }//GEN-LAST:event_cashVarActionPerformed

    //true là bằng CASH, mặc định là CASH, false là CARD
    private void cardVarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardVarActionPerformed
        // TODO add your handling code here:
        if (cardVar.isSelected() == true){
            cashAndCard = false;
        }
    }//GEN-LAST:event_cardVarActionPerformed

    private void confirmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmBtnActionPerformed

    private void clearBillBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBillBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clearBillBtnActionPerformed

    private void clearBillBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearBillBtnMouseClicked
        // TODO add your handling code here:
        ProdTotal = 0;
        smallTotal = 0;
        bigTotal = 0;
        numberOfProduct = 0;
        
        billVar.setText("Your bill: " + smallTotal + " vnđ");
        paymentVar.setText("Your fee: " + 0 + " vnđ");
        allPaymentVar.setText("All your payment is:" + bigTotal + " vnđ");

        String[]columnName = {"PRODUCT","PRICE","QUANTITY","TOTAL"};
        DefaultTableModel model = (DefaultTableModel)ProductTable2.getModel();
        model.setRowCount(0);
        //        model.setColumnIdentifiers(columnName);
        ProductTable2.getColumnModel().getColumn(0).setPreferredWidth(65);
        ProductTable2.getColumnModel().getColumn(1).setPreferredWidth(10);
        ProductTable2.getColumnModel().getColumn(2).setPreferredWidth(10);
        ProductTable2.getColumnModel().getColumn(3).setPreferredWidth(10);
    }//GEN-LAST:event_clearBillBtnMouseClicked

    private void RefreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RefreshBtnActionPerformed
//ArrayList<ListOfProducts> list = new ArrayList<ListOfProducts>();
//TheModelProduct model = new TheModelProduct(rows, columnName);
//ProductTable.setModel(model);
    private void clearTable(){
        ((DefaultTableModel)ProductTable.getModel()).setNumRows(0);
    }
    private void RefreshBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RefreshBtnMouseClicked
        // TODO add your handling code here:
//        DefaultTableModel model2 = (DefaultTableModel)ProductTable.getModel();
//        ProductTable.setModel(DbUtils.resultSetToTableModel(Rs));
        String typeTemp = null;
        try{
            Con = JDBCConnection.getConnection("kubi", "28112001");
            St = (Statement) Con.createStatement();

            if (fillterBox.getSelectedItem() == "Stationery"){
//                clearTable();
                typeTemp = "01";
                ArrayList<ListOfProducts> list = new ArrayList();
                Rs = St.executeQuery("select ProductName, Unit, Price, NoInventory, Img from dbo.PRODUCT WHERE ProdTypeID =" + typeTemp);
                ListOfProducts p;
                while(Rs.next()){
                    p = new ListOfProducts(
                                    Rs.getString("ProductName"),
                                    Rs.getString("Unit"),
                                    Rs.getInt("Price"),
                                    Rs.getInt("NoInventory"),
                                    Rs.getString("Img")
                            );
                list.add(p);
                }
                populateJTable2(list);
            }
            else if (fillterBox.getSelectedItem() == "Electric Appliances"){
                typeTemp = "02";
                ArrayList<ListOfProducts> list = new ArrayList();
                Rs = St.executeQuery("select ProductName, Unit, Price, NoInventory, Img from dbo.PRODUCT WHERE ProdTypeID =" + typeTemp);
                ListOfProducts p;
                while(Rs.next()){
                    p = new ListOfProducts(
                                    Rs.getString("ProductName"),
                                    Rs.getString("Unit"),
                                    Rs.getInt("Price"),
                                    Rs.getInt("NoInventory"),
                                    Rs.getString("Img")
                            );
                    list.add(p);
                    }
                populateJTable2(list);
            } else if (fillterBox.getSelectedItem() == "Kitchen Utensils & Appliances"){
                typeTemp = "03";
                ArrayList<ListOfProducts> list = new ArrayList();
                Rs = St.executeQuery("select ProductName, Unit, Price, NoInventory, Img from dbo.PRODUCT WHERE ProdTypeID =" + typeTemp);
                ListOfProducts p;
                while(Rs.next()){
                    p = new ListOfProducts(
                                    Rs.getString("ProductName"),
                                    Rs.getString("Unit"),
                                    Rs.getInt("Price"),
                                    Rs.getInt("NoInventory"),
                                    Rs.getString("Img")
                            );
                    list.add(p);
                    }
                populateJTable2(list);
            } else if (fillterBox.getSelectedItem() == "Phone Accessories"){
                typeTemp = "04";
                ArrayList<ListOfProducts> list = new ArrayList();
                Rs = St.executeQuery("select ProductName, Unit, Price, NoInventory, Img from dbo.PRODUCT WHERE ProdTypeID =" + typeTemp);
                ListOfProducts p;
                while(Rs.next()){
                    p = new ListOfProducts(
                                    Rs.getString("ProductName"),
                                    Rs.getString("Unit"),
                                    Rs.getInt("Price"),
                                    Rs.getInt("NoInventory"),
                                    Rs.getString("Img")
                            );
                    list.add(p);
                    }
                populateJTable2(list);
            } else if (fillterBox.getSelectedItem() == "Detergents"){
                typeTemp = "05";
                ArrayList<ListOfProducts> list = new ArrayList();
                Rs = St.executeQuery("select ProductName, Unit, Price, NoInventory, Img from dbo.PRODUCT WHERE ProdTypeID =" + typeTemp);
                ListOfProducts p;
                while(Rs.next()){
                    p = new ListOfProducts(
                                    Rs.getString("ProductName"),
                                    Rs.getString("Unit"),
                                    Rs.getInt("Price"),
                                    Rs.getInt("NoInventory"),
                                    Rs.getString("Img")
                            );
                    list.add(p);
                    }
                populateJTable2(list);
            } else if (fillterBox.getSelectedItem() == "Beauty & Personal Care"){
                typeTemp = "06";
                ArrayList<ListOfProducts> list = new ArrayList();
                Rs = St.executeQuery("select ProductName, Unit, Price, NoInventory, Img from dbo.PRODUCT WHERE ProdTypeID =" + typeTemp);
                ListOfProducts p;
                while(Rs.next()){
                    p = new ListOfProducts(
                                    Rs.getString("ProductName"),
                                    Rs.getString("Unit"),
                                    Rs.getInt("Price"),
                                    Rs.getInt("NoInventory"),
                                    Rs.getString("Img")
                            );
                    list.add(p);
                    }
                populateJTable2(list);
            }else if (fillterBox.getSelectedItem() == "Food"){
                typeTemp = "07";
                ArrayList<ListOfProducts> list = new ArrayList();
                Rs = St.executeQuery("select ProductName, Unit, Price, NoInventory, Img from dbo.PRODUCT WHERE ProdTypeID =" + typeTemp);
                ListOfProducts p;
                while(Rs.next()){
                    p = new ListOfProducts(
                                    Rs.getString("ProductName"),
                                    Rs.getString("Unit"),
                                    Rs.getInt("Price"),
                                    Rs.getInt("NoInventory"),
                                    Rs.getString("Img")
                            );
                    list.add(p);
                    }
                populateJTable2(list);
            }else if (fillterBox.getSelectedItem() == "Beverage"){
                typeTemp = "08";
                ArrayList<ListOfProducts> list = new ArrayList();
                Rs = St.executeQuery("select ProductName, Unit, Price, NoInventory, Img from dbo.PRODUCT WHERE ProdTypeID =" + typeTemp);
                ListOfProducts p;
                while(Rs.next()){
                    p = new ListOfProducts(
                                    Rs.getString("ProductName"),
                                    Rs.getString("Unit"),
                                    Rs.getInt("Price"),
                                    Rs.getInt("NoInventory"),
                                    Rs.getString("Img")
                            );
                    list.add(p);
                    }
                populateJTable2(list);
            }else if (fillterBox.getSelectedItem() == "Lower 50k"){
                ArrayList<ListOfProducts> list = new ArrayList();
                Rs = St.executeQuery("select ProductName, Unit, Price, NoInventory, Img from dbo.PRODUCT WHERE Price <" + 50000 + "Order by Price ASC");
                ListOfProducts p;
                while(Rs.next()){
                    p = new ListOfProducts(
                                    Rs.getString("ProductName"),
                                    Rs.getString("Unit"),
                                    Rs.getInt("Price"),
                                    Rs.getInt("NoInventory"),
                                    Rs.getString("Img")
                            );
                    list.add(p);
                    }
                populateJTable2(list);
            }else if (fillterBox.getSelectedItem() == "50k to 500k"){
                ArrayList<ListOfProducts> list = new ArrayList();
                Rs = St.executeQuery("select ProductName, Unit, Price, NoInventory, Img from dbo.PRODUCT WHERE Price >=" + 50000 + " AND Price <="+ 500000 + "Order by Price ASC");
                ListOfProducts p;
                while(Rs.next()){
                    p = new ListOfProducts(
                                    Rs.getString("ProductName"),
                                    Rs.getString("Unit"),
                                    Rs.getInt("Price"),
                                    Rs.getInt("NoInventory"),
                                    Rs.getString("Img")
                            );
                    list.add(p);
                    }
                populateJTable2(list);
            }else if (fillterBox.getSelectedItem() == "Higher 500k"){
                ArrayList<ListOfProducts> list = new ArrayList();
                Rs = St.executeQuery("select ProductName, Unit, Price, NoInventory, Img from dbo.PRODUCT WHERE Price >" + 500000 + "Order by Price ASC");
                ListOfProducts p;
                while(Rs.next()){
                    p = new ListOfProducts(
                                    Rs.getString("ProductName"),
                                    Rs.getString("Unit"),
                                    Rs.getInt("Price"),
                                    Rs.getInt("NoInventory"),
                                    Rs.getString("Img")
                            );
                    list.add(p);
                    }
                populateJTable2(list);
            }else if (fillterBox.getSelectedItem() == "All"){
                ArrayList<ListOfProducts> list = new ArrayList();
                Rs = St.executeQuery("select ProductName, Unit, Price, NoInventory, Img from dbo.PRODUCT Order by Price ASC");
                ListOfProducts p;
                while(Rs.next()){
                    p = new ListOfProducts(
                                    Rs.getString("ProductName"),
                                    Rs.getString("Unit"),
                                    Rs.getInt("Price"),
                                    Rs.getInt("NoInventory"),
                                    Rs.getString("Img")
                            );
                    list.add(p);
                    }
                populateJTable2(list);
            }
            
//            Rs = St.executeQuery("select ProductName, NoInventory, Price from dbo.PRODUCT WHERE ProdTypeID =" + typeTemp);
//            ProductTable.getColumnModel().getColumn(0).setPreferredWidth(150);
//            ProductTable.setRowHeight(25);
//            ProductTable.setModel(DbUtils.resultStToTableModel(Rs));
        } catch (Exception e){
            e.printStackTrace();
        }

    }//GEN-LAST:event_RefreshBtnMouseClicked

    private void AddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddBtnActionPerformed

    private void AddBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddBtnMouseClicked
        // TODO add your handling code here:
        //        if(quanVar.getText().isEmpty() || nameVar.getText().isEmpty()) {
            //            JOptionPane.showMessageDialog(this, "You're not chossing product !!!");
            //        } else{
            //            i++;
            //            if (i == 1){
                //                    billText.setText(billText.getText() +
                    //                        "                   ********** PEELADAZ **********\n" +
                    //                        "NUM      PRODUCT             PRICE     QUANTITY     TOTAL\n" + i +
                    //                        "         " + nameVar.getText() +
                    //                        "     " + Uprice +
                    //                        "     " + quanVar.getText() +
                    //                        "     " + ProdTotal + "\n");
                //            }
            //            else {
                //                    billText.setText(billText.getText() +
                    //                        i +
                    //                        "         " + nameVar.getText() +
                    //                        "     " + Uprice +
                    //                        "     " + quanVar.getText() +
                    //                        "     " + ProdTotal + "\n");
                //
                //            }
            //        }
        if(nameVar.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "You're not chossing product !!!");
        }else if((Integer)quanVar2.getValue() <= 0 ){
            JOptionPane.showMessageDialog(this, "Please take one or more product !!!");
        } else {
            numberOfProduct++;
            ProdTotal = Uprice * (Integer)quanVar2.getValue();
            smallTotal = ProdTotal + smallTotal;
            bigTotal = smallTotal + (smallTotal / 100 )* 10;

            billVar.setText("Your bill: " + smallTotal + " vnđ");
            if ((smallTotal / 100 )* 10 < 12000){
                feeDelivery = 12000;
                paymentVar.setText("Your fee: 12000 vnđ");
            } else {
                paymentVar.setText("Your fee: " + (smallTotal / 100 )* 10 + " vnđ");
                feeDelivery = (smallTotal / 100 )* 10;
            }
            //        paymentVar.setText("Your fee: " + (smallTotal / 100 )* 7 + " vnđ");
            allPaymentVar.setText("All your payment is:" + bigTotal + " vnđ");

            //        Object[] rows = new Object[5];
            String[]columnName = {"PRODUCT","PRICE","QUANTITY","TOTAL"};
            DefaultTableModel model = (DefaultTableModel)ProductTable2.getModel();
            //        model.setColumnIdentifiers(columnName);
            ProductTable2.getColumnModel().getColumn(0).setPreferredWidth(65);
            ProductTable2.getColumnModel().getColumn(1).setPreferredWidth(10);
            ProductTable2.getColumnModel().getColumn(2).setPreferredWidth(10);
            ProductTable2.getColumnModel().getColumn(3).setPreferredWidth(10);

            model.addRow(new Object[]{nameVar.getText(), Uprice,quanVar2.getValue(),ProdTotal});

            int bfQTY2 = 0;

            //        afQTY = String.valueOf(bfQTY - bfQTY2 - Integer.valueOf(quanVar2.getText));
            bfQTY2 = bfQTY;
            //        UpdateQTY();
        }
        
    }//GEN-LAST:event_AddBtnMouseClicked

    private void priceVarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceVarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceVarActionPerformed

    private void fillterBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fillterBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fillterBoxActionPerformed

    private void nameVarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameVarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameVarActionPerformed

    private void ProductTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductTableMouseClicked
        // TODO add your handling code here:
        //        DefaultTableModel model = (DefaultTableModel)ProductTable.getModel ();
        int Myindex = ProductTable.getSelectedRow();
        nameVar.setText(ProductTable.getValueAt(Myindex, 0).toString());
        priceVar.setText(ProductTable.getValueAt(Myindex, 2).toString());
//        bfQTY = Integer.valueOf(ProductTable.getValueAt(Myindex, 1).toString());   
//        priceVar.setText(model.getValueAt(Myindex, 2).toString());
        
        Uprice = Integer.valueOf(ProductTable.getValueAt(Myindex, 2).toString());
        //        quanVar2.setText(ProductTable.getValueAt(Myindex, 3).toString());
        //
        //        Uprice = Integer.valueOf(model.getValueAt(Myindex, 2).toString());
    }//GEN-LAST:event_ProductTableMouseClicked

    private void confirmBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmBtnMouseClicked
        // TODO add your handling code here:
        ArrayList<Receipt> list = new ArrayList();
        Receipt temp = new Receipt(null, null, feeDelivery, cashAndCard, listRD);   
        
    }//GEN-LAST:event_confirmBtnMouseClicked
    ArrayList<Receipt_Detail> listRD = new ArrayList();
    private void fromJtableToArray(){
        
        DefaultTableModel model = (DefaultTableModel)ProductTable2.getModel();
        
        for (int i = 0; model.getRowCount() > i; i++) {
            final String col1 = (String) model.getValueAt(i, 0);
            final String col2 = (String) model.getValueAt(i, 1);
            final String col3 = (String) model.getValueAt(i, 2);
            Receipt_Detail temp = new Receipt_Detail(null,col1,col2,col3);
            //id, name,price,QTY
            listRD.add(temp);
        }
    }
int Uprice = 0;
int ProdTotal = 0;
int bigTotal = 0;
int smallTotal = 0;
int feeDelivery = 0;
int bfQTY = 0;
String afQTY = null;
int numberOfProduct = 0;
boolean cashAndCard = true;    
    public void UpdateQTY(){
        try{
            JDBCConnection.getConnection("kubi", "28112001");
            PreparedStatement add = Con.prepareStatement("UPDATE PRODUCT SET NoInventory = ? WHERE ProductName = ?");
            
            add.setString(1, afQTY);
            add.setString(2, nameVar.getText());

            add.executeUpdate();
//            SelectProduct();
//            JOptionPane.showMessageDialog(this, "Information have been Updated !!!");
        }catch(SQLException e){
            e.printStackTrace();
        }
        
    }
//    public void SelectProduct() {
//        try{
//            Con = JDBCConnection.getConnection("kubi", "28112001");
//            St = (Statement) Con.createStatement();
//            Rs = St.executeQuery("select ProductName, NoInventory, Price from dbo.PRODUCT Order by Price ASC");
//            BillTable.setModel(DbUtils.resultSetToTableModel(Rs));
//        } catch (Exception e){
//            e.printStackTrace();
//        }
//        BillTable.getColumnModel().getColumn(0).setPreferredWidth(150);
//        BillTable.setRowHeight(25);
//    } 
    
    public void populateJTable () throws MalformedURLException, IOException {
//        DefaultTableModel model =(DefaultTableModel) ProductTabel.getModel();
        QueryForProduct mq = new QueryForProduct();
        ArrayList<ListOfProducts> list = mq.BindTable();
        String[]columnName = {"Name","Unit","Price","No Inventory","Image"};
        Object[][] rows = new Object [list.size()][5];
        for (int i = 0; i < list.size (); i++) {
            rows[i][0] = list.get(i).getProductName();
            rows[i][1] = list.get(i).getUnit();
            rows[i][2] = list.get(i).getPrice();
            rows[i][3] = list.get(i).getNoProd();
            if(list.get(i).getImg() != null){
//                String link = null;
//                link = list.get(i).getImg();
                URL url = new URL(list.get(i).getImg());
                Image image = ImageIO.read(url);
                Image imagee = image.getScaledInstance(120, 120,  java.awt.Image.SCALE_SMOOTH);
                ImageIcon picture = new ImageIcon(imagee);   
                rows[i][4] = picture;
            }
            else{
                rows[i][4] = null;
            }
        }
        
        TheModelProduct model = new TheModelProduct(rows, columnName);
////        JTable model = new JTable(rows, columnName);
        ProductTable.setModel(model);
        ProductTable.setRowHeight(120);
//            int rows2 = ProductTable.getRowCount();
//
//            int cols2 = ProductTable.getColumnCount();
//
//            for (int ii = 0; ii < rows2 ; ii++) {
//
//                    for ( int k  = 0; k < cols2 ; k++) {
//
//                    for (int h = 0; h < list.size(); h++) {
//
//                        String b = list.get(h);
//                        b = ProductTable.getValueAt(ii, k).toString();
//
//                    }
//                }
//            }
        
        DefaultTableCellRenderer rendar = new DefaultTableCellRenderer();
        rendar.setHorizontalAlignment(jLabel1.CENTER);

        ProductTable.getColumnModel().getColumn(0).setCellRenderer(rendar);
        ProductTable.getColumnModel().getColumn(1).setCellRenderer(rendar); 
        ProductTable.getColumnModel().getColumn(2).setCellRenderer(rendar); 
        ProductTable.getColumnModel().getColumn(3).setCellRenderer(rendar); 
//        ProductTable.getColumnModel().getColumn(4).setCellRenderer(rendar); 

        ProductTable.getColumnModel().getColumn(0).setPreferredWidth(75);
        ProductTable.getColumnModel().getColumn(1).setPreferredWidth(25);
        ProductTable.getColumnModel().getColumn(2).setPreferredWidth(30);
        ProductTable.getColumnModel().getColumn(3).setPreferredWidth(30);
        ProductTable.getColumnModel().getColumn(4).setPreferredWidth(120);
        
        String[]columnName2 = {"PRODUCT","PRICE","QUANTITY","TOTAL"};
        DefaultTableModel model2 = (DefaultTableModel)ProductTable2.getModel();
        model2.setColumnIdentifiers(columnName2);
        
//        ProductTable2.getColumnModel().getColumn(0).setPreferredWidth(10);
//        ProductTable2.getColumnModel().getColumn(1).setPreferredWidth(10);
//        ProductTable2.getColumnModel().getColumn(2).setPreferredWidth(10);
//        ProductTable2.getColumnModel().getColumn(3).setPreferredWidth(10);
    }
    
    public void populateJTable2 (ArrayList<ListOfProducts> list2) throws MalformedURLException, IOException {
//        QueryForProduct mq = new QueryForProduct();
//        ArrayList<ListOfProducts> list = mq.BindTable();
        String[]columnName = {"Name","Unit","Price","No Inventory","Image"};
        Object[][] rows = new Object [list2.size()][5];
        for (int i = 0; i < list2.size (); i++) {
            rows[i][0] = list2.get(i).getProductName();
            rows[i][1] = list2.get(i).getUnit();
            rows[i][2] = list2.get(i).getPrice();
            rows[i][3] = list2.get(i).getNoProd();
            if(list2.get(i).getImg() != null){
//                String link = null;
//                link = list.get(i).getImg();
                URL url = new URL(list2.get(i).getImg());
                Image image = ImageIO.read(url);
                Image imagee = image.getScaledInstance(120, 120,  java.awt.Image.SCALE_SMOOTH);
                ImageIcon picture = new ImageIcon(imagee);   
                rows[i][4] = picture;
            }
            else{
                rows[i][4] = null;
            }
        }
        
        TheModelProduct model = new TheModelProduct(rows, columnName);
        ProductTable.setModel(model);
        ProductTable.setRowHeight(120);
        
        DefaultTableCellRenderer rendar = new DefaultTableCellRenderer();
        rendar.setHorizontalAlignment(jLabel1.CENTER);

        ProductTable.getColumnModel().getColumn(0).setCellRenderer(rendar);
        ProductTable.getColumnModel().getColumn(1).setCellRenderer(rendar); 
        ProductTable.getColumnModel().getColumn(2).setCellRenderer(rendar); 
        ProductTable.getColumnModel().getColumn(3).setCellRenderer(rendar); 
//        ProductTable.getColumnModel().getColumn(4).setCellRenderer(rendar); 

        ProductTable.getColumnModel().getColumn(0).setPreferredWidth(75);
        ProductTable.getColumnModel().getColumn(1).setPreferredWidth(25);
        ProductTable.getColumnModel().getColumn(2).setPreferredWidth(30);
        ProductTable.getColumnModel().getColumn(3).setPreferredWidth(30);
        ProductTable.getColumnModel().getColumn(4).setPreferredWidth(120);
        
        
    }
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ShowProduct().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(ShowProduct.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });   
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBtn;
    private javax.swing.JTable ProductTable;
    private javax.swing.JTable ProductTable2;
    private javax.swing.JButton RefreshBtn;
    private javax.swing.JLabel allPaymentVar;
    private javax.swing.JLabel billVar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton cardVar;
    private javax.swing.JRadioButton cashVar;
    private javax.swing.JButton clearBillBtn;
    private javax.swing.JButton confirmBtn;
    private javax.swing.JComboBox<String> fillterBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField nameVar;
    private javax.swing.JLabel paymentVar;
    private javax.swing.JTextField priceVar;
    private javax.swing.JSpinner quanVar2;
    // End of variables declaration//GEN-END:variables
}
