USE qlbh_onl
GO

--SELECT * FROM PARTNERS
--SELECT * FROM BRANCH

--CHẠY TRANS 2
EXEC USP_CyDL2 'Nguyen Gia Minh', '277 Nguyen Van Cu', 'DT0001', 'CN0001'

--SELECT * FROM PARTNERS
--SELECT * FROM BRANCH
