USE qlbh_onl
GO

--SELECT * FROM PARTNERS
--SELECT * FROM BRANCH

--CHẠY TRANS 1
EXEC USP_CyDL1 'Nguyen Gia Minh', '277 Nguyen Van Cu', 'DT0001', 'CN0001'

--SELECT * FROM PARTNERS
--SELECT * FROM BRANCH
